security:
    encoders:
        ServerBundle\Model\User:
            algorithm:  bcrypt
            cost:       12

    providers:
        database_user:
            entity:
                class: ServerBundle\Model\User

    role_hierarchy:
        ROLE_USER:     []
        ROLE_UPLOADER: [ROLE_USER]
        ROLE_ADMIN:    [ROLE_UPLOADER, ROLE_USER]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
