services:
#    server.example:
#        class: ServerBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    upload_service:
        class: ServerBundle\Service\UploadService
        arguments: ["@doctrine.orm.default_entity_manager", "%target_path%"]