services:
    name_normalizer:
        class: ServerBundle\Service\NameNormalizer
    upload_service:
        class: ServerBundle\Service\UploadService
        arguments: ["@doctrine.orm.default_entity_manager", "@name_normalizer", "%target_path%"]
